function architecture(){var ib='',fb=' top: -1000px;',Fb='" for "gwt:onLoadErrorFn"',Db='" for "gwt:onPropertyErrorFn"',ob='");',Gb='#',Sb='&',Ac='.cache.js',Ib='/',Ob='//',ic='06358BBBAB4B34208C8C71326857BE3B',kc='0A80B3C02B2D04A8B6F07938F89C3D83',lc='1956C604F2FFA9E39815D955F1D830A4',mc='5D356D2CD14220AFF72A7B6A0225FE6F',oc='603929786E91CC0BBD5601C6C5945A4A',pc='6B1D1EB56BCA49E8BE677A0799259E89',qc='6E6DE4F0353F59F5D9DD4339CCAB0B9D',rc='97516B0C2F9BAAFC45DB2F295791C336',zc=':',xb='::',Ic=':moduleBase',Ub=';',hb='<!doctype html>',jb='<html><head><\/head><body><\/body><\/html>',Ab='=',Hb='?',sc='A5A1F7B13935F351000CA5796434E9A1',tc='AE0D5EE70B6DF4A74C4D525ABED29A65',Cb='Bad handler "',gb='CSS1Compat',mb='Chrome',uc='DAEFF938468990C46BF758C9E313E0D2',vc='DE1441CE8E287C7E98E3E6FC6331A9C8',wc='DF7A9CF2B465548CD9CAD1BDA2ECD9AD',lb='DOMContentLoaded',ab='DUMMY',xc='E419E3942575E84A2D421FB4BD5DFA81',yc='E5368B3845E49A4867B78CACC26CEB17',Tb='GWT_LOCALE=',Hc='Ignoring non-whitelisted Dev Mode URL: ',Xb='Unexpected exception in locale detection, using default: ',Vb='_',Gc='__gwtDevModeHook:architecture',Wb='__gwt_Locale',Fc='_gwt_dummy_',$='architecture',hc='architecture.devmode.js',Mb='architecture.nocache.js',wb='architecture::',Nb='base',Lb='baseUrl',X='begin',bb='body',W='bootstrap',Kb='clear.cache.gif',zb='content',jc='default',nc='en',Cc='end',nb='eval("',Ec='file:',Qb='fr',dc='gecko',ec='gecko1_8',Y='gwt.codesvr.architecture=',Z='gwt.codesvr=',Eb='gwt:onLoadErrorFn',Bb='gwt:onPropertyErrorFn',yb='gwt:property',tb='head',Dc='http:',ac='ie10',cc='ie8',bc='ie9',cb='iframe',Jb='img',qb='javascript',db='javascript:""',Bc='loadExternalRefs',Pb='locale',Rb='locale=',ub='meta',sb='moduleRequested',rb='moduleStartup',_b='msie',vb='name',eb='position:absolute; width:0; height:0; border:none; left: -1000px;',$b='safari',pb='script',gc='selectingPermutation',_='startup',kb='undefined',fc='unknown',Yb='user.agent',Zb='webkit';var u=window;var v=document;A(W,X);function w(){var a=u.location.search;return a.indexOf(Y)!=-1||a.indexOf(Z)!=-1}
function A(a,b){if(u.__gwtStatsEvent){u.__gwtStatsEvent({moduleName:$,sessionId:u.__gwtStatsSessionId,subSystem:_,evtGroup:a,millis:(new Date).getTime(),type:b})}}
architecture.__sendStats=A;architecture.__moduleName=$;architecture.__errFn=null;architecture.__moduleBase=ab;architecture.__softPermutationId=0;architecture.__computePropValue=null;architecture.__getPropMap=null;architecture.__gwtInstallCode=function(){};architecture.__gwtStartLoadingFragment=function(){return null};var B=function(){return false};var C=function(){return null};__propertyErrorFunction=null;var D=u.__gwt_activeModules=u.__gwt_activeModules||{};D[$]={moduleName:$};var F;function G(){I();return F}
function H(){I();return F.getElementsByTagName(bb)[0]}
function I(){if(F){return}var a=v.createElement(cb);a.src=db;a.id=$;a.style.cssText=eb+fb;a.tabIndex=-1;v.body.appendChild(a);F=a.contentDocument;if(!F){F=a.contentWindow.document}F.open();var b=document.compatMode==gb?hb:ib;F.write(b+jb);F.close()}
function J(k){function l(a){function b(){if(typeof v.readyState==kb){return typeof v.body!=kb&&v.body!=null}return /loaded|complete/.test(v.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(v.removeEventListener){v.removeEventListener(lb,d,false)}if(e){clearInterval(e)}}}
if(v.addEventListener){v.addEventListener(lb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=H();var f=G();var g;if(navigator.userAgent.indexOf(mb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(nb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ob));g=f.createElement(pb);g.language=qb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(pb);g.language=qb;g.text=c[i];e.appendChild(g);d(e,g)}}}
architecture.onScriptDownloaded=function(a){l(function(){m(a)})};A(rb,sb);var n=v.createElement(pb);n.src=k;v.getElementsByTagName(tb)[0].appendChild(n)}
architecture.__startLoadingFragment=function(a){return M(a)};architecture.__installRunAsyncCode=function(a){var b=H();var c=G().createElement(pb);c.language=qb;c.text=a;b.appendChild(c);b.removeChild(c)};function K(){var c={};var d;var e;var f=v.getElementsByTagName(ub);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(vb),k;if(j){j=j.replace(wb,ib);if(j.indexOf(xb)>=0){continue}if(j==yb){k=i.getAttribute(zb);if(k){var l,m=k.indexOf(Ab);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=ib}c[j]=l}}else if(j==Bb){k=i.getAttribute(zb);if(k){try{d=eval(k)}catch(a){alert(Cb+k+Db)}}}else if(j==Eb){k=i.getAttribute(zb);if(k){try{e=eval(k)}catch(a){alert(Cb+k+Fb)}}}}}C=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;architecture.__errFn=e}
function L(){function e(a){var b=a.lastIndexOf(Gb);if(b==-1){b=a.length}var c=a.indexOf(Hb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ib,Math.min(c,b));return d>=0?a.substring(0,d+1):ib}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=v.createElement(Jb);b.src=a+Kb;a=e(b.src)}return a}
function g(){var a=C(Lb);if(a!=null){return a}return ib}
function h(){var a=v.getElementsByTagName(pb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Mb)!=-1){return e(a[b].src)}}return ib}
function i(){var a=v.getElementsByTagName(Nb);if(a.length>0){return a[a.length-1].href}return ib}
function j(){var a=v.location;return a.href==a.protocol+Ob+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ib){k=h()}if(k==ib){k=i()}if(k==ib&&j()){k=e(v.location.href)}k=f(k);return k}
function M(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return architecture.__moduleBase+a}
function N(){var m=[];var n=0;function o(a,b){var c=m;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var p=[];var q=[];function r(a){var b=q[a](),c=p[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
q[Pb]=function(){var b=null;var c=Qb;try{if(!b){var d=location.search;var e=d.indexOf(Rb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Sb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){var h=v.cookie;var i=h.indexOf(Tb);if(i>=0){var g=h.indexOf(Ub,i);if(g<0){g=h.length}b=h.substring(i+11,g)}}if(!b){b=C(Pb)}if(!b){var j=navigator.browserLanguage?navigator.browserLanguage:navigator.language;if(j){var k=j.split(/[-_]/);if(k.length>1){k[1]=k[1].toUpperCase()}b=k.join(Vb)}}if(!b){b=u[Wb]}if(b){c=b}while(b&&!B(Pb,b)){var l=b.lastIndexOf(Vb);if(l<0){b=null;break}b=b.substring(0,l)}}catch(a){alert(Xb+a)}u[Wb]=c;return b||Qb};p[Pb]={'default':0,en:1,fr:2};q[Yb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Zb)!=-1}())return $b;if(function(){return b.indexOf(_b)!=-1&&v.documentMode>=10}())return ac;if(function(){return b.indexOf(_b)!=-1&&v.documentMode>=9}())return bc;if(function(){return b.indexOf(_b)!=-1&&v.documentMode>=8}())return cc;if(function(){return b.indexOf(dc)!=-1}())return ec;return fc};p[Yb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};B=function(a,b){return b in p[a]};architecture.__getPropMap=function(){var a={};for(var b in p){if(p.hasOwnProperty(b)){a[b]=r(b)}}return a};architecture.__computePropValue=r;u.__gwt_activeModules[$].bindings=architecture.__getPropMap;A(W,gc);if(w()){return M(hc)}var s;try{o([Qb,cc],ic);o([jc,ac],kc);o([Qb,$b],lc);o([jc,$b],mc);o([nc,ec],oc);o([Qb,ec],pc);o([nc,ac],qc);o([nc,cc],rc);o([nc,bc],sc);o([nc,$b],tc);o([jc,cc],uc);o([jc,ec],vc);o([jc,bc],wc);o([Qb,ac],xc);o([Qb,bc],yc);s=m[r(Pb)][r(Yb)];var t=s.indexOf(zc);if(t!=-1){n=parseInt(s.substring(t+1),10);s=s.substring(0,t)}}catch(a){}architecture.__softPermutationId=n;return M(s+Ac)}
function O(){if(!u.__gwt_stylesLoaded){u.__gwt_stylesLoaded={}}A(Bc,X);A(Bc,Cc)}
K();architecture.__moduleBase=L();D[$].moduleBase=architecture.__moduleBase;var P=N();if(u){var Q=!!(u.location.protocol==Dc||u.location.protocol==Ec);u.__gwt_activeModules[$].canRedirect=Q;function R(){var b=Fc;try{u.sessionStorage.setItem(b,b);u.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(Q&&R()){var S=Gc;var T=u.sessionStorage[S];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(T)){if(T&&(window.console&&console.log)){console.log(Hc+T)}T=ib}if(T&&!u[S]){u[S]=true;u[S+Ic]=L();var U=v.createElement(pb);U.src=T;var V=v.getElementsByTagName(tb)[0];V.insertBefore(U,V.firstElementChild||V.children[0]);return false}}}O();A(W,Cc);J(P);return true}
architecture.succeeded=architecture();